version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    ports: 
        - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false    #Disables auth & HTTPS. Perfect for local development
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  #Limits memory usage
    volumes:
      - esdata:/usr/share/elasticsearch/data
    # unlimits:
    #   memlocks:
    #     soft: -1
    #     hard: -1


  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1   #Elasticsearch and kibana must be of same version 
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local